DECLARE
  CURSOR CR_CIDADE IS
    SELECT * FROM CIDADE;
BEGIN
   FOR ST_CIDADE IN 1 .. 10 LOOP
      DBMS_OUTPUT.put_line(ST_CIDADE);
    END LOOP;
  
    FOR ST_CIDADE IN CR_CIDADE LOOP
      DBMS_OUTPUT.put_line(ST_CIDADE.DS_CIDADE);
    END LOOP;
    
  FOR ST_CIDADE IN 1 .. 100 LOOP
    IF MOD(ST_CIDADE,2) = 0 THEN 
       INSERT INTO CIDADE (DS_CIDADE, CD_UF) VALUES (ST_CIDADE, 'CE');
    ELSE
     INSERT INTO CIDADE (DS_CIDADE, CD_UF) VALUES (ST_CIDADE, 'AM');
    END IF;
  END LOOP;  
  
  FOR ST_CIDADE IN 1 .. 100 LOOP
    INSERT INTO CIDADE (DS_CIDADE, CD_UF) VALUES (ST_CIDADE, 'CE');
  END LOOP;

  /*FOR ST_CIDADE IN 1 .. 100 LOOP
    DELETE FROM CIDADE WHERE MOD(CD_CIDADE, 2) = 0;
  END LOOP;*/

  /*FOR ST_CIDADE IN CR_CIDADE LOOP
    DELETE FROM CIDADE WHERE  MOD(CD_CIDADE, 2)!=0;
  END LOOP;*/
  COMMIT;
END;
--TRUNCATE TABLE CIDADE

--SELECT * FROM UF
