/*SELECT * FROM TB_PESSOA

alter table tb_pessoa add constraint ck_tp_pessoa check(tp_pessoa in ('F','J'));*/

DECLARE
TYPE PESSOA_TYPE IS TABLE OF TB_PESSOA%ROWTYPE
INDEX BY PLS_INTEGER;     

LISTA_PESSOA PESSOA_TYPE;

BEGIN
  SELECT * BULK COLLECT INTO LISTA_PESSOA FROM TB_PESSOA;
  
  FOR I IN 1..LISTA_PESSOA.COUNT
    LOOP
    DBMS_OUTPUT.put_line(LISTA_PESSOA(I).NM_PESSOA);
  END LOOP;
END; 
